################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 7070)
    port: "${HOST_PORT}"

################################################################################
##                               Database options                             ##
################################################################################
database:
    host: "${DATABASE_HOST}"
    user: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
    database: "${DATABASE_NAME}"
    scheme: "${DATABASE_SCHEME}"
    port: "${DATABASE_PORT}"
    connectionTimeoutMillis: 5000
    max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: ${LOGGING_LEVEL}

################################################################################
##                             Scheduler options                              ##
################################################################################
scheduler:
    enable: true
    items:
        - name: bridge
          enable: true
          expression: "*/10 * * * * *"

bridge:
    networkAName: "production_main"
    networkABridgeAddress: "${A_BRIDGE_CONTRACT_ADDRESS}"
    networkATokenAddress: "${A_TOKEN_CONTRACT_ADDRESS}"
    networkBName: "production_side"
    networkBBridgeAddress: "${B_BRIDGE_CONTRACT_ADDRESS}"
    networkBTokenAddress: "${B_TOKEN_CONTRACT_ADDRESS}"
    validators:
        - "${BRIDGE_VALIDATOR_KEY}"
